// READ-ONLY: confirm UD-DRY-00039 is COMPLETED and the stock moved correctly.
import { prisma } from '../lib/prisma.js';

async function main() {
  const proc = await prisma.dryingProcess.findUnique({
    where: { batchNumber: 'UD-DRY-00039' },
    include: {
      DryingProcessItem: { include: { WoodType: true, Warehouse: true } },
    },
  });
  if (!proc) { console.log('Not found'); return; }

  console.log('=== UD-DRY-00039 ===');
  console.log({
    status: proc.status,
    endTime: proc.endTime?.toISOString() ?? null,
    totalCost: proc.totalCost,
    updatedAt: proc.updatedAt.toISOString(),
  });
  console.log('\nNotes (history):\n' + (proc.notes || '(empty)'));

  const items = (proc as any).DryingProcessItem || [];
  console.log(`\n=== Items (${items.length}) ===`);
  for (const item of items) {
    console.log({
      woodType: item.WoodType?.name,
      thickness: item.thickness,
      pieceCount: item.pieceCount,
      sourceWarehouse: item.Warehouse?.name,
    });

    const stock = await prisma.stock.findFirst({
      where: {
        warehouseId: item.sourceWarehouseId,
        woodTypeId: item.woodTypeId,
        thickness: item.thickness,
      },
    });
    console.log('  current stock:', {
      statusNotDried: (stock as any)?.statusNotDried,
      statusUnderDrying: (stock as any)?.statusUnderDrying,
      statusDried: (stock as any)?.statusDried,
      expected: `UnderDrying should be 0 (was ${item.pieceCount}); Dried should be ≥${item.pieceCount}`,
    });
  }

  console.log('\n=== Notifications generated by approval ===');
  const recent = await prisma.notification.findMany({
    where: {
      type: { in: ['DRYING_CLOSE_APPROVED', 'DRYING_CLOSE_REQUESTED', 'DRYING_CLOSE_REJECTED', 'DRYING_REOPENED'] },
      createdAt: { gte: new Date(Date.now() - 24 * 60 * 60 * 1000) },
    },
    orderBy: { createdAt: 'desc' },
    select: { type: true, title: true, message: true, createdAt: true, isRead: true, userId: true },
  });
  console.log(JSON.stringify(recent, null, 2));
}

main().catch(e => { console.error(e); process.exit(1); }).finally(() => prisma.$disconnect());
