CREATE TABLE IF NOT EXISTS "WoodReceipt" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "woodTypeId" TEXT NOT NULL,
  "supplier" TEXT NOT NULL,
  "receiptDate" TIMESTAMP(3) NOT NULL,
  "purchaseOrder" TEXT,
  "status" TEXT NOT NULL DEFAULT 'PENDING',
  "notes" TEXT,
  "totalAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "totalVolumeM3" DOUBLE PRECISION,
  "totalPieces" INTEGER,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "WoodReceipt_woodTypeId_fkey" FOREIGN KEY ("woodTypeId") REFERENCES "WoodType"("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);
