// Service worker registration script for development mode
// This file is automatically generated by vite-plugin-pwa

if ('serviceWorker' in navigator) {
  // Register the service worker
  navigator.serviceWorker.register('/dev-dist/sw.js', {
    type: 'module',
    scope: '/'
  }).then((registration) => {
    console.log('Service Worker registered with scope:', registration.scope);

    // Check for updates
    registration.addEventListener('updatefound', () => {
      const newWorker = registration.installing;
      console.log('Service Worker update found');

      newWorker?.addEventListener('statechange', () => {
        if (newWorker.state === 'installed' && navigator.serviceWorker.controller) {
          console.log('New Service Worker installed, update available');
        }
      });
    });
  }).catch((error) => {
    console.log('Service Worker registration failed:', error);
  });
}
