// Development service worker placeholder
// This file is automatically generated by vite-plugin-pwa in development mode

self.addEventListener('install', () => {
  console.log('Service worker installing in development mode');
  self.skipWaiting();
});

self.addEventListener('activate', () => {
  console.log('Service worker activating in development mode');
  self.clients.claim();
});

self.addEventListener('fetch', (event) => {
  // In development mode, don't intercept any requests
  // Just let them pass through naturally without using respondWith
  return;
});
