name: Deploy

on:
  push:
    branches: 
      - main
      - staging
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Deploy Backend
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        cd backend
        npm install -g vercel
        vercel pull --yes --environment=production --token ${{ secrets.VERCEL_TOKEN }}
        npx prisma generate
        vercel build --prod --token ${{ secrets.VERCEL_TOKEN }}
        vercel deploy --prebuilt --prod --token ${{ secrets.VERCEL_TOKEN }}

    - name: Deploy Frontend
      run: |
        cd frontend
        npm install -g vercel
        npm install
        vercel pull --yes --environment=production --token ${{ secrets.VERCEL_TOKEN }}
        vercel build --prod --token ${{ secrets.VERCEL_TOKEN }}
        vercel deploy --prebuilt --prod --token ${{ secrets.VERCEL_TOKEN }} 